export const stateList: string[] = ["CO", "ID", "WA"];

export const productTags: string[] = [
  "Grain",
  "Wheat",
  "Rye",
  "Barley",
  "Oats",
  "Triticale",
  "Spelt",
  "Emmer",
  "Einkorn",
  "Heirloom/Landrace Wheat",
  "Heirloom/Landrace Barley",
  "Heirloom/Landrace Rye",
  "Buckwheat",
  "Quinoa",
  "Proso Millet",
  "Pearl Millet",
  "Millets",
  "Sorghum",
  "Sorghum (White)",
  "Sorghum (Red)",
  "Rice",
  "Legumes & Pulses",
  "Chickpeas (Garbanzo - Desi & Kabuli)",
  "Lentils",
  "Peas (all kinds)",
  "Beans (all general beans: great northerns, red, black, etc.)",
  "Black beans",
  "Cranberry beans",
  "Dark red kidney beans",
  "Great northern beans",
  "Green baby lima beans",
  "Light red kidney beans",
  "Pink beans",
  "Pinto beans",
  "Small red beans",
  "Small white beans",
  "Oilseeds & Others",
  "Canola",
  "Soy",
  "Sunflower",
  "Safflower",
  "Flax",
  "Mustard",
  "Rapeseed (not canola variety)",
  "Forage & Fodder Crops",
  "Hay",
  "Hay (Timothy, Alfalfa, Clover, Fescue, Brome, etc.)",
  "Grass",
  "Other Crops",
  "Hemp",
  "Forbes (Kochia)",
  "Wildflowers",
  "Cotton",
  "Potato",
  "Sugar beets",
  "Milo (grain sorghum)",
  "Corn",
  "Vegetables (radish, cabbage, carrots, chicory, onion, coriander)",
  "Fats & Oils",
];

export const orgTypes: string[] = ["Distributor", "Processor", "Producer"];

export const orgSubTypes: string[] = [
  "Storage",
  "Milling/Malting/Cleaning",
  "Food Manufacturing",
  "Farming",
  "Brokerage",
  "Equipment Manufacturing",
];
